import os

docs = {
    "orchestrator.py": '"""\nModule: orchestrator.py\nPurpose: Securely coordinates Text-to-SQL and Semantic Document Retrieval systems.\nResponsibilities: Validates queries, delegates execution to appropriate tools, and formats LLM context.\nSecurity Boundaries: Strictly firewalls LLMs from the raw databases and documents. Exposes only heavily bounded snippets.\nKey Decisions: Abstracted the final context generation natively so the orchestrator inherently enforces data access limits.\nInputs: User query, environment name, optional generated SQL.\nOutputs: Traced, token-optimized LLM response payload.\n"""\n',
    "sql_guard.py": '"""\nModule: sql_guard.py\nPurpose: A robust firewall safely executing LLM-generated SQL against SQLite.\nResponsibilities: Syntax validation, table whitelist enforcement, schema checking, and query execution tracing.\nSecurity Boundaries: The ultimate native defense layer. Restricts all SQLite execution connections to `query_only = ON` to block data-mutation injections natively regardless of LLM output.\nKey Decisions: Utilizes `EXPLAIN` to validate table and column existence securely natively via the engine rather than complex regex parsing.\nInputs: Raw SQL string, DB path, environment.\nOutputs: Validated execution rows or structured rejection trace.\n"""\n',
    "csv_loader.py": '"""\nModule: csv_loader.py\nPurpose: Modular CSV ingestion engine loading raw operational files into structured SQLite databases.\nResponsibilities: Handles transaction rolling, normalization routing, and validation mapping during table loading.\nSecurity Boundaries: Enforces isolated datasets; guarantees no silent failures on invalid primary keys.\nKey Decisions: Implemented purely row-by-row state evaluation to provide meticulous error log traceability instead of batch-failing.\nInputs: CSV paths, database connection, duplicate-checking state sets.\nOutputs: Standardized database rows and structured metric summaries.\n"""\n',
    "validators.py": '"""\nModule: validators.py\nPurpose: Non-destructive data validation and schema integrity layer.\nResponsibilities: Enforces numerical boundaries, date logic, unique ID integrity, and cross-table foreign key rules prior to ingestion.\nSecurity Boundaries: Purely functional evaluation logic; makes absolutely zero database mutations.\nKey Decisions: Differentiates validation strictness dynamically between the messy NeonPlay (Startup) and strict VistaStream (Enterprise) environments.\nInputs: Raw dictionary rows.\nOutputs: Structured validation result payloads (`valid`, `severity`, `message`).\n"""\n',
    "normalizers.py": '"""\nModule: normalizers.py\nPurpose: Operational data cleanup and string standardization utility.\nResponsibilities: Trims whitespace, unifies capitalizations, and standardizes geography/device terminology via mapping dictionaries.\nSecurity Boundaries: Mutates only text formatting; explicitly relies on the validators.py module for handling true structural failures.\nKey Decisions: Highly active manipulation for Startup datasets to prove automated handling; mostly pass-through behavior for clean Enterprise data.\nInputs: Raw cell values, field names.\nOutputs: Standardized strings and log records.\n"""\n',
    "retrieval_tools.py": '"""\nModule: retrieval_tools.py\nPurpose: The functional unified tool interface exposed to LLM orchestration agents.\nResponsibilities: Provides discrete semantic document search and structured SQL execution endpoints.\nSecurity Boundaries: Automatically filters results down to strict limits (e.g. 15 rows) to prevent LLM context window blowouts.\nKey Decisions: Enforces explicit `table_references` outputs for absolute hallucination prevention and traceability mapping.\nInputs: Queries, dataset environment strings.\nOutputs: Standardized dictionary outputs formatted via clean Markdown converters.\n"""\n',
    "embedding_pipeline.py": '"""\nModule: embedding_pipeline.py\nPurpose: Initializes ChromaDB embeddings and bridges the semantic layout back to SQLite.\nResponsibilities: Chroma client initialization, upsert batching, and dual-system synchronization.\nSecurity Boundaries: Utilizes dedicated collection namespaces to strictly prevent Startup and Enterprise semantic cross-contamination.\nKey Decisions: Utilizes a dynamic two-step commit to ensure the relational DB `embedding_id` perfectly matches the finalized Chroma state.\nInputs: SQLite connection, parsed chunk payloads.\nOutputs: Persistent vector collections and SQLite relation updates.\n"""\n',
    "pdf_chunker.py": '"""\nModule: pdf_chunker.py\nPurpose: PyMuPDF textual extraction and logical semantic chunking pipeline.\nResponsibilities: Recursively parses unstructured PDFs, extracts plain text layouts, applies token-optimized chunk overlaps dynamically.\nSecurity Boundaries: Gracefully isolates and skips malformed or encrypted documents without crashing batch jobs.\nKey Decisions: Employs stable MD5 chunk hashing algorithms to guarantee idempotent pipeline reruns and absolute granular traceability.\nInputs: PDF directory paths.\nOutputs: Traceable chunk dictionaries with mapped metadata.\n"""\n'
}

for filename, docstring in docs.items():
    if not os.path.exists(filename):
        print(f"Skipping {filename}: not found.")
        continue
    with open(filename, "r", encoding="utf-8") as f:
        content = f.read()
    if content.startswith('"""'):
        print(f"Skipping {filename}: already has a docstring.")
        continue
    with open(filename, "w", encoding="utf-8") as f:
        f.write(docstring + "\n" + content)
    print(f"Added docstring to {filename}")
